#!/bin/bash
set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

if [[ $# -eq 0 ]] ; then
    $DIR/compile
    cd $DIR/build
    ctest -j8
    cd -
else
    if [[ $# -eq 1 ]] ; then
        $DIR/build/tests/test_$1
    else
        echo "Wrong number of arguments"
        exit 1
    fi
fi

